def get_all_currency():
    currency = ["pUSD",
                "pBNB",
                "pBRL",
                "pCAD",
                "pCHF",
                "pCNY",
                "pDASH",
                "pDCR",
                "pETH",
                "pEUR",
                "pGBP",
                "pHKD",
                "pINR",
                "pJPY",
                "pKRW",
                "pLTC",
                "pMXN",
                "pPHP",
                "pRVN",
                "pSGD",
                "pXAG",
                "pXAU",
                "pXBC",
                "pXBT",
                "pXLM",
                "pXMR",
                "pZEC"]

    return currency

